import { expect, test } from "bun:test";
import { mkdtemp, readFile, rm, stat } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";

import {
  createClaudeHooksConfiguration,
  createCodexHooksConfiguration,
  renderClaudeDispatcherSource,
  renderCodexDispatcherSource,
  resolveHookifyInstallProvenance,
  writeCodexDispatcherSource,
} from "./index";

test("resolveHookifyInstallProvenance fills actor and timestamp defaults", () => {
  const provenance = resolveHookifyInstallProvenance({
    installSurface: "codex-user-hooks-json",
    installedVia: "skill:hookify-install",
    environment: {
      USER: "jasonkuhrt",
    },
    now: new Date("2026-04-03T15:30:00.000Z"),
  });

  expect(provenance).toEqual({
    installSurface: "codex-user-hooks-json",
    installedVia: "skill:hookify-install",
    installedBy: "jasonkuhrt",
    installedAt: "2026-04-03T15:30:00.000Z",
  });
});

test("renderCodexDispatcherSource includes install provenance in the generated banner", () => {
  const source = renderCodexDispatcherSource({
    importPath: "@hookify/integration-codex",
    provenance: {
      installSurface: "codex-plugin",
      installedVia: "plugin:hookify@hookify-local",
      installedBy: "jasonkuhrt",
      installedAt: "2026-04-03T15:30:00.000Z",
    },
  });

  expect(source).toContain("#!/usr/bin/env bun");
  expect(source).toContain("// Generated by Hookify install.");
  expect(source).toContain("// Agent: codex");
  expect(source).toContain("// Install surface: codex-plugin");
  expect(source).toContain("// Installed via: plugin:hookify@hookify-local");
  expect(source).toContain("// Installed by: jasonkuhrt");
  expect(source).toContain("// Installed at: 2026-04-03T15:30:00.000Z");
  expect(source).toContain('} from "@hookify/integration-codex";');
});

test("renderClaudeDispatcherSource includes install provenance in the generated banner", () => {
  const source = renderClaudeDispatcherSource({
    importPath: "@hookify/integration-claude",
    provenance: {
      installSurface: "claude-plugin",
      installedVia: "skill:hookify-install",
      installedBy: "jasonkuhrt",
      installedAt: "2026-04-03T15:31:00.000Z",
    },
  });

  expect(source).toContain("// Agent: claude");
  expect(source).toContain("// Install surface: claude-plugin");
  expect(source).toContain('} from "@hookify/integration-claude";');
});

test("writeCodexDispatcherSource writes an executable generated file", async () => {
  const workspacePath = await mkdtemp(join(tmpdir(), "hookify-install-"));

  try {
    const dispatcherPath = join(workspacePath, "dispatch-codex.ts");

    await writeCodexDispatcherSource({
      pathname: dispatcherPath,
      importPath: "@hookify/integration-codex",
      provenance: {
        installSurface: "codex-user-hooks-json",
        installedVia: "skill:hookify-install",
        installedBy: "jasonkuhrt",
        installedAt: "2026-04-03T15:32:00.000Z",
      },
    });

    const [source, metadata] = await Promise.all([
      readFile(dispatcherPath, "utf8"),
      stat(dispatcherPath),
    ]);

    expect(source).toContain("// Installed by: jasonkuhrt");
    expect(metadata.mode & 0o111).not.toBe(0);
  } finally {
    await rm(workspacePath, { recursive: true, force: true });
  }
});

test("createCodexHooksConfiguration renders the Bash matcher only where Codex requires it", () => {
  expect(
    createCodexHooksConfiguration({
      command: "bun ~/.codex/hooks/hookify.ts",
    }),
  ).toEqual({
    hooks: {
      PreToolUse: [
        {
          matcher: "Bash",
          hooks: [
            {
              type: "command",
              command: "bun ~/.codex/hooks/hookify.ts",
            },
          ],
        },
      ],
      PostToolUse: [
        {
          matcher: "Bash",
          hooks: [
            {
              type: "command",
              command: "bun ~/.codex/hooks/hookify.ts",
            },
          ],
        },
      ],
      SessionStart: [
        {
          hooks: [
            {
              type: "command",
              command: "bun ~/.codex/hooks/hookify.ts",
            },
          ],
        },
      ],
      UserPromptSubmit: [
        {
          hooks: [
            {
              type: "command",
              command: "bun ~/.codex/hooks/hookify.ts",
            },
          ],
        },
      ],
      Stop: [
        {
          hooks: [
            {
              type: "command",
              command: "bun ~/.codex/hooks/hookify.ts",
            },
          ],
        },
      ],
    },
  });
});

test("createClaudeHooksConfiguration renders the current Hookify Claude install set", () => {
  expect(
    createClaudeHooksConfiguration({
      command: "bun ${CLAUDE_PLUGIN_ROOT}/hooks/dispatch-claude.ts",
      timeoutSeconds: 10,
    }),
  ).toEqual({
    description: "Hookify Claude install",
    hooks: {
      SessionStart: [
        {
          hooks: [
            {
              type: "command",
              command: "bun ${CLAUDE_PLUGIN_ROOT}/hooks/dispatch-claude.ts",
              timeout: 10,
            },
          ],
        },
      ],
      UserPromptSubmit: [
        {
          hooks: [
            {
              type: "command",
              command: "bun ${CLAUDE_PLUGIN_ROOT}/hooks/dispatch-claude.ts",
              timeout: 10,
            },
          ],
        },
      ],
      PreToolUse: [
        {
          hooks: [
            {
              type: "command",
              command: "bun ${CLAUDE_PLUGIN_ROOT}/hooks/dispatch-claude.ts",
              timeout: 10,
            },
          ],
        },
      ],
      PermissionRequest: [
        {
          hooks: [
            {
              type: "command",
              command: "bun ${CLAUDE_PLUGIN_ROOT}/hooks/dispatch-claude.ts",
              timeout: 10,
            },
          ],
        },
      ],
      PostToolUse: [
        {
          hooks: [
            {
              type: "command",
              command: "bun ${CLAUDE_PLUGIN_ROOT}/hooks/dispatch-claude.ts",
              timeout: 10,
            },
          ],
        },
      ],
      PostToolUseFailure: [
        {
          hooks: [
            {
              type: "command",
              command: "bun ${CLAUDE_PLUGIN_ROOT}/hooks/dispatch-claude.ts",
              timeout: 10,
            },
          ],
        },
      ],
      Notification: [
        {
          hooks: [
            {
              type: "command",
              command: "bun ${CLAUDE_PLUGIN_ROOT}/hooks/dispatch-claude.ts",
              timeout: 10,
            },
          ],
        },
      ],
      Stop: [
        {
          hooks: [
            {
              type: "command",
              command: "bun ${CLAUDE_PLUGIN_ROOT}/hooks/dispatch-claude.ts",
              timeout: 10,
            },
          ],
        },
      ],
      SubagentStop: [
        {
          hooks: [
            {
              type: "command",
              command: "bun ${CLAUDE_PLUGIN_ROOT}/hooks/dispatch-claude.ts",
              timeout: 10,
            },
          ],
        },
      ],
      PreCompact: [
        {
          hooks: [
            {
              type: "command",
              command: "bun ${CLAUDE_PLUGIN_ROOT}/hooks/dispatch-claude.ts",
              timeout: 10,
            },
          ],
        },
      ],
      SessionEnd: [
        {
          hooks: [
            {
              type: "command",
              command: "bun ${CLAUDE_PLUGIN_ROOT}/hooks/dispatch-claude.ts",
              timeout: 10,
            },
          ],
        },
      ],
    },
  });
});
