import { expect, test } from "bun:test";
import { lstat, mkdir, mkdtemp, readFile, realpath, rm } from "node:fs/promises";
import { dirname, join } from "node:path";
import { tmpdir } from "node:os";
import { spawn } from "node:child_process";

const repoRootPath = join(import.meta.dir, "..");

test("install-codex sets up the generated local plugin bridge and cleans legacy user hooks", async () => {
  const workspacePath = await mkdtemp(join(tmpdir(), "hookify-install-codex-"));

  try {
    const homeDirectoryPath = join(workspacePath, "home");
    const hookifyHomePath = join(homeDirectoryPath, ".local", "share", "hookify");
    const codexHooksPath = join(homeDirectoryPath, ".codex", "hooks.json");
    const codexConfigPath = join(homeDirectoryPath, ".codex", "config.toml");
    const marketplacePath = join(homeDirectoryPath, ".agents", "plugins", "marketplace.json");
    const installScriptPath = join(import.meta.dir, "install-codex.ts");

    await mkdir(dirname(codexHooksPath), { recursive: true });
    await mkdir(dirname(marketplacePath), { recursive: true });
    await Bun.write(
      codexHooksPath,
      JSON.stringify(
        {
          hooks: {
            PreToolUse: [
              {
                matcher: "Bash",
                hooks: [
                  {
                    type: "command",
                    command: "bun ~/.codex/hooks/hookify.ts",
                  },
                  {
                    type: "command",
                    command: "bun ~/.codex/hooks/keep-me.ts",
                  },
                ],
              },
            ],
          },
        },
        null,
        2,
      ),
    );
    await Bun.write(codexConfigPath, 'model = "gpt-5.4"\n');

    const childProcess = spawn("bun", [installScriptPath], {
      cwd: repoRootPath,
      env: {
        ...process.env,
        HOME: homeDirectoryPath,
        HOOKIFY_HOME: hookifyHomePath,
        HOOKIFY_REPO_DIR: repoRootPath,
        HOOKIFY_INSTALL_ACTOR: "test-runner",
        HOOKIFY_INSTALLED_VIA: "test:install-codex",
      },
      stdio: ["ignore", "pipe", "pipe"],
    });

    const stdoutChunks: Buffer[] = [];
    const stderrChunks: Buffer[] = [];

    childProcess.stdout.on("data", (chunk) => {
      stdoutChunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
    });
    childProcess.stderr.on("data", (chunk) => {
      stderrChunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
    });

    const exitCode = await new Promise<number | null>((resolve, reject) => {
      childProcess.once("error", reject);
      childProcess.once("close", resolve);
    });
    const stdout = Buffer.concat(stdoutChunks).toString("utf8");
    const stderr = Buffer.concat(stderrChunks).toString("utf8");

    expect(exitCode).toBe(0);
    expect(stderr).toBe("");
    expect(stdout).toContain("Hookify for Codex installed.");

    const generatedPluginPath = join(hookifyHomePath, "plugins", "hookify");
    const generatedDispatcherPath = join(generatedPluginPath, "hooks", "dispatch-codex.ts");
    const pluginLinkPath = join(homeDirectoryPath, "plugins", "hookify");
    const generatedHooksJsonPath = join(generatedPluginPath, "hooks.json");
    const generatedManifestPath = join(generatedPluginPath, ".codex-plugin", "plugin.json");
    const generatedSkillsPath = join(generatedPluginPath, "skills");
    const generatedAgentsPath = join(generatedPluginPath, "agents");

    const [
      dispatcherSource,
      hooksJsonText,
      configText,
      marketplaceText,
      cleanedHooksText,
      manifestText,
      skillsMetadata,
      agentsMetadata,
      pluginLinkMetadata,
    ] = await Promise.all([
      readFile(generatedDispatcherPath, "utf8"),
      readFile(generatedHooksJsonPath, "utf8"),
      readFile(codexConfigPath, "utf8"),
      readFile(marketplacePath, "utf8"),
      readFile(codexHooksPath, "utf8"),
      readFile(generatedManifestPath, "utf8"),
      lstat(generatedSkillsPath),
      lstat(generatedAgentsPath),
      lstat(pluginLinkPath),
    ]);

    expect(dispatcherSource).toContain("// Generated by Hookify install.");
    expect(dispatcherSource).toContain("// Install surface: codex-plugin");
    expect(dispatcherSource).toContain("// Installed via: test:install-codex");
    expect(dispatcherSource).toContain("// Installed by: test-runner");
    expect(dispatcherSource).toContain(
      `} from ${JSON.stringify(join(repoRootPath, "packages", "integration-codex", "src", "index.ts"))};`,
    );
    expect(JSON.parse(hooksJsonText)).toEqual({
      hooks: {
        PreToolUse: [
          {
            matcher: "Bash",
            hooks: [
              {
                type: "command",
                command: "bun ./hooks/dispatch-codex.ts",
              },
            ],
          },
        ],
        PostToolUse: [
          {
            matcher: "Bash",
            hooks: [
              {
                type: "command",
                command: "bun ./hooks/dispatch-codex.ts",
              },
            ],
          },
        ],
        SessionStart: [
          {
            hooks: [
              {
                type: "command",
                command: "bun ./hooks/dispatch-codex.ts",
              },
            ],
          },
        ],
        UserPromptSubmit: [
          {
            hooks: [
              {
                type: "command",
                command: "bun ./hooks/dispatch-codex.ts",
              },
            ],
          },
        ],
        Stop: [
          {
            hooks: [
              {
                type: "command",
                command: "bun ./hooks/dispatch-codex.ts",
              },
            ],
          },
        ],
      },
    });
    expect(configText).toContain("[features]");
    expect(configText).toContain("codex_hooks = true");
    expect(configText).toContain('[plugins."hookify@hookify-local"]');
    expect(configText).toContain("enabled = true");
    expect(JSON.parse(marketplaceText)).toEqual({
      name: "hookify-local",
      interface: {
        displayName: "Hookify local",
      },
      plugins: [
        {
          name: "hookify",
          source: {
            source: "local",
            path: "./plugins/hookify",
          },
          policy: {
            installation: "AVAILABLE",
            authentication: "ON_INSTALL",
          },
          category: "Productivity",
        },
      ],
    });
    expect(JSON.parse(cleanedHooksText)).toEqual({
      hooks: {
        PreToolUse: [
          {
            matcher: "Bash",
            hooks: [
              {
                type: "command",
                command: "bun ~/.codex/hooks/keep-me.ts",
              },
            ],
          },
        ],
      },
    });
    expect(JSON.parse(manifestText).name).toBe("hookify");
    expect(skillsMetadata.isSymbolicLink()).toBe(true);
    expect(agentsMetadata.isSymbolicLink()).toBe(true);
    expect(pluginLinkMetadata.isSymbolicLink()).toBe(true);
    expect(await realpath(generatedSkillsPath)).toBe(
      await realpath(join(repoRootPath, "plugins", "hookify", "skills")),
    );
    expect(await realpath(generatedAgentsPath)).toBe(
      await realpath(join(repoRootPath, "plugins", "hookify", "agents")),
    );
    expect(await realpath(pluginLinkPath)).toBe(await realpath(generatedPluginPath));
  } finally {
    await rm(workspacePath, { recursive: true, force: true });
  }
});
